http:
  port: '8080'

tcp_socket:
  port: '7070'

distributed_lock:
  port: '4444'

logger:
  filename: 'server-A.log'
  level: 'debug'

storage:
  messages_file_path: 'messages-A.json'

syncer:
  http:
    port: '9090'

neighbour:
  http:
    port: '8081'
  tcp_socket:
    port: '7071'
  syncer:
    http:
      port: '9091'