http:
  port: '8081'

tcp_socket:
  port: '7071'

distributed_lock:
  port: '4444'

logger:
  filename: 'server-B.log'
  level: 'debug'

neighbour:
  http:
    port: '8080'
  tcp_socket:
    port: '7070'
