http:
  port: '8080'

tcp_socket:
  port: '7070'

distributed_lock:
  port: '4444'

logger:
  filename: 'server-A.log'
  level: 'debug'

neighbour:
  http:
    port: '8081'
  tcp_socket:
    port: '7071'
